# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tftp2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btftp2.proto\x>

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tftp2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODE._serialized_start=990
  _MODE._serialized_end=1031
  _ERRORCODE._serialized_start=1034
  _ERRORCODE._serialized_end=1187
  _REQ._serialized_start=22
  _REQ._serialized_end=69
  _DATA._serialized_start=71
  _DATA._serialized_end=111
  _ACK._serialized_start=113
  _ACK._serialized_end=135
  _ERROR._serialized_start=137
  _ERROR._serialized_end=181
  _PATH._serialized_start=183
  _PATH._serialized_end=203
  _LISTRESPONSE._serialized_start=205
  _LISTRESPONSE._serialized_end=251
  _LISTITEM._serialized_start=253
  _LISTITEM._serialized_end=330
  _FILE._serialized_start=332
  _FILE._serialized_end=369
  _MOVE._serialized_start=371
  _MOVE._serialized_end=415
  _SEARCHITEM._serialized_start=417
  _SEARCHITEM._serialized_end=457
  _SEARCHRESPONSE._serialized_start=459
  _SEARCHRESPONSE._serialized_end=509
  _SEARCH._serialized_start=511
  _SEARCH._serialized_end=549
  _RMDIR._serialized_start=551
  _RMDIR._serialized_end=587
  _MENSAGEM._serialized_start=590
  _MENSAGEM._serialized_end=988
# @@protoc_insertion_point(module_scope)


